title: 

description: >- 
  
baseurl: ""
url: "https://alain-tissier.com"

sass:
  style: compressed


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

social_links:
    github: alaintis
    linkedin: alain-tissier

theme: minima

header_pages:
  - index.md
  - works.md
  - cv.md
  - about.md





